### ISSUE TITLE
Aufrufziel Exception - 9e31d7e0-4263-441c-8ad3-890aa8ea556c

### ISSUE THREAD

**Issue by js1251** [js1251/bspProtect-support#17]
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei shared_bspFormat.LumpMap.GetInstance(Int32 index, Byte[] bytes)
   bei shared_bspFormat.Bsp.CreateLumps(BinaryReader reader)
   bei shared_bspFormat.Bsp..ctor(FileSystemInfo fileInfo)
   bei client_protection.BspProcessing.BspValidator..ctor(FileInfo bspFileInfo)
   bei client_application.MVVM.ViewModel.ProtectionTab.BspSelectViewModel.Process()
   bei client_application.MVVM.ViewModel.BaseViewModel.ProcessHelper(Object sender, DoWorkEventArgs args)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

An error occurred in the software. @js1251 will reach out to you soon. Updates will be posted here.

**Comment by js1251** [comment]
Invalid / already protected BSPs

**Comment by L0rdReaver** [comment]
why does the bsp not work?
its not protected and its playable

**Comment by js1251** [comment]
Was related to non standard UTF8 chars. Fixed in later versions of bspProtect
